class CardInfo {
  final int position;
  final String name;
  final String iconImage;
  final String suit;
  final String upright;
  final String reversed;
  final String yesOrNo;
  final String description;
  final List<String> images;

  CardInfo(
    this.position, {
    this.name,
    this.iconImage,
    this.suit,
    this.upright,
    this.reversed,
    this.yesOrNo,
    this.description,
    this.images,
  });
}

List<CardInfo> cardDeck = [
  CardInfo(1,
      name: 'The Fool',
      iconImage: 'assets/major/tarot-fool.jpg',
      suit: 'Major Arcana',
      upright: 'New beginnings, innocence, adventure',
      reversed: 'Recklessness, fearlessness, risk',
      yesOrNo: 'Yes',
      description:
          'The Fool tarot card is the number 0 of the Major Arcana, which stands for the number of unlimited potentials. To see the Fool tarot card generally indicates that you are on the verge of an unexpected and exciting new adventure. This may require you to take a blind leap of faith. There will be a rewarding experience that will contribute to your growth as a human being. The new adventure could be a literal one and may involve traveling to a new land or territories you’ve never visited before.',
      images: []),
  CardInfo(2,
      name: 'The Magician',
      iconImage: 'assets/major/tarot-magician.jpg',
      suit: 'Major Arcana',
      upright: 'Willpower, creation, manifestation',
      reversed: 'Manipulation, illusions',
      yesOrNo: 'Yes',
      description:
          'The Magician tarot card reveals how your wishes and desires can be realized through determination and willpower. When this card shows up in your reading, you can be assured that you have the drive to make your dreams happen. Just remember that you are powerful and if you create your inner world, the outer will follow. Yet, you have to focus and concentrate on achieving your dream. Get rid of any discretions and make a detailed plan to stay on track.',
      images: []),
  CardInfo(3,
      name: 'The High Priestess',
      iconImage: 'assets/major/tarot-highpriestess.jpg',
      suit: 'Major Arcana',
      upright: 'Intuitive, unconscious, divine feminine',
      reversed: 'Repressed feelings, withdrawal, silence',
      yesOrNo: 'Yes',
      description:
          'When the High Priestess appears upright in a tarot reading she usually indicates a time for learning and listening to your intuition rather than prioritizing your intellect and conscious mind. She tells you to slow down and reflect on what you’ve learned and to acquire even more knowledge before making a decision or taking action. Often being considered as the gatekeeper at the ancient temples, the High Priestess can also show up in a tarot reading when you are facing a “gatekeeper” in your daily life. Her advice is to stop worrying about the outcome and trust the decision of the gatekeepers.',
      images: []),
  CardInfo(4,
      name: 'The Empress',
      iconImage: 'assets/major/tarot-empress.jpg',
      suit: 'Major Arcana',
      upright: 'Femininity, nurturing, fertility, abundance',
      reversed: 'Dependence, smothering, emptiness',
      yesOrNo: 'Yes',
      description:
          'The upright Empress tarot card in a reading calls on you to connect with your feminine side. This can be translated in many ways – think of creativity, elegance, sensuality, fertility, and nurturing. She tells you to be kind to yourself and search for beauty and happiness in your life. The Empress often brings strong bursts of creative or artistic energy. This creative energy may not only be in the form of a painting or art project, but also in other forms of expressing yourself creatively, like music or drama.',
      images: []),
  CardInfo(5,
      name: 'The Emperor',
      iconImage: 'assets/major/tarot-emperor.jpg',
      suit: 'Major Arcana',
      upright: 'Authority, structure, a father figure',
      reversed: 'Excessive control, rigidity, domination',
      yesOrNo: 'Yes',
      description:
          'As the counterpart of the Empress, the Emperor signifies the husband who is constant and trustworthy. He is confident, in control of his emotions, and an example of masculine energy. He is the paternal figure in life that brings structure and security, creates rules and systems, and conveys knowledge. As a ruler, he leads with a firm hand and demands respect and authority. With careful planning, a highly organized approach, and perseverance, the Emperor can overcome any problem that’s thrown at him. This new level of mastery won’t just happen. You have to pursue your goals similar to the way that the Emperor does, structured, strategically, and with a lot of perseverance.',
      images: []),
  CardInfo(6,
      name: 'The Hierophant',
      iconImage: 'assets/major/tarot-hierophant.jpg',
      suit: 'Major Arcana',
      upright: 'Spiritual wisdom, tradition, conformity, morality, ethics',
      reversed: 'Rebellion, subversiveness, freedom, personal beliefs',
      yesOrNo: 'Neutral',
      description:
          'When the Hierophant tarot card is upright in a reading, it represents a necessity to follow existing conventions, rules, or a well-established procedure. It advises you to maintain conventional boundaries that are considered a standard method. Rather than being inventive and breaking norms, you will be familiarized with certain traditions, beliefs, and systems which are existing already for quite a long time. The Hierophant tarot card embodies a customary set of spiritual beliefs and is frequently associated with religion and other formal ideologies. Thus, this card suggests that you learn the necessary values from a trusted source such as a mentor or a spiritual counselor.',
      images: []),
  CardInfo(7,
      name: 'The Lovers',
      iconImage: 'assets/major/tarot-lovers.jpg',
      suit: 'Major Arcana',
      upright: 'Love, harmony, partnerships, choices',
      reversed: 'Disbalance, one-sidedness, disharmony',
      yesOrNo: 'Yes',
      description:
          'The Lovers tarot card in the upright position can imply that you have major life-changing choices to make or are faced with a dilemma. Temptation is often part of that choice or dilemma. You may feel unsure about what direction you should take or who to trust. Or you may have to choose between contradicting and equally unifying options. The Lovers in tarot advises you to not automatically go for the easy road (temptation). First, gather the information you need to make the right decision. If you face the problem and contemplate it wisely, it’ll lead you on to greater things.',
      images: []),
  CardInfo(8,
      name: 'The Chariot',
      iconImage: 'assets/major/tarot-chariot.jpg',
      suit: 'Major Arcana',
      upright: 'Direction, control, willpower, determination, success, action',
      reversed:
          'Lack of control, opposition, lack of direction, self-discipline',
      yesOrNo: 'Yes',
      description:
          'When the upright Chariot tarot card shows up in a tarot reading, it tells you that now is the time to get what you want. Consider this card as a sign of encouragement. The Chariot tarot card is all about overcoming obstacles and achieving your goal through determination, focus, and willpower. You will feel motivated, ambitious, and in control. This will help you to get a stagnant situation moving again and overcome all the challenges that may be in your path. Just keep focused and believe in your own abilities and you will achieve your goal. The Chariot tells you that a triumph is waiting for you and that you are fully in control of making it happen. This may mean that you have to compete with others or that you find yourself in a situation that feels like a battle. You’re pulled in opposite directions or you feel like your strength and confidence are being tested.',
      images: []),
  CardInfo(9,
      name: 'Strength',
      iconImage: 'assets/major/tarot-strength.jpg',
      suit: 'Major Arcana',
      upright: 'Strength, courage, compassion, focus, persuasion, influence',
      reversed: 'Self-doubt, weakness, insecurity, low energy, raw emotion',
      yesOrNo: 'Yes',
      description:
          'The upright Strength tarot card represents – as the name already suggests – strength, courage, persuasion, and patience. It tells you that you have the power and strength to overcome any obstacle – just like the Chariot. However, when pulling the strength, you’ll need to act with grace and sensitivity, rather than just using brutal force. The card also tells you that you have the capacity to stay positive and calm and think logically in stressful situations that test your patience and strength. Be it through compassion, cunning, or understanding, Strength signifies that you can obtain true control of a situation, and not simply the power to forcefully impose your will. The Strength tarot card indicates that you are a very persevering person and that you can achieve anything you set your mind to. You’re confident and do not have problems being yourself and speaking up. You are committed to what you need to do, and you go about it in a very balanced and mature way. Keep behaving this way and you will be successful in anything you want to accomplish.',
      images: []),
  CardInfo(10,
      name: 'The Hermit',
      iconImage: 'assets/major/tarot-hermit.jpg',
      suit: 'Major Arcana',
      upright:
          'Wisdom, soul searching, solitude, spiritual enlightenment, receiving or giving guidance',
      reversed:
          'Loneliness, isolation, paranoia, sadness, being overcome or paralyzed by fear',
      yesOrNo: 'Yes',
      description:
          'In the upright position, the Hermit is a compelling card. Just as beacons of light often guide ships to the shore, this sage is ushering in a period of personal growth and exploration. The Hermit represents wisdom earned by seeking the highest truth. Often, looking for answers within requires time alone with few distractions. It requires introspection and concentrating less on the senses. Although this can seem a little scary at first, committing to a personal quest for truth can be one of the most rewarding experiences of life.',
      images: []),
  CardInfo(11,
      name: 'Wheel of Fortune',
      iconImage: 'assets/major/tarot-wheeloffortune.jpg',
      suit: 'Major Arcana',
      upright: 'Chance, destiny and fate, karma, turning points, life cycles',
      reversed:
          'Upheaval, lousy luck, unwelcome change, setbacks, external forces',
      yesOrNo: 'Yes',
      description:
          'The Wheel of Fortune is ruled by Jupiter, the planet of good fortune and expansion. If the Wheel of Fortune tarot card arrives upright, you are in luck. Whether you believe in destiny or not, things are lining up for your benefit. Think of surprising offers and new opportunities. Your personal vision will also increase as life’s tempo cranks up. The Wheel of Fortune tarot card can also reveal psychic abilities, either within you or someone close. Consider this as a chance to discover more about yourself and to listen to your gut. Manifest your dreams, now that your energy is aligning with your spirit guides, angels, and other helpers. You can’t control the powers of the universe, but you can definitely grow your understanding of your role in this life and the universe. Just remember that there is nothing to fear. Everything will work out according to divine intervention and timing.',
      images: []),
  CardInfo(12,
      name: 'Justice',
      iconImage: 'assets/major/tarot-justice.jpg',
      suit: 'Major Arcana',
      upright:
          'Fairness, integrity, legal disputes, cause and effect, life lessons',
      reversed:
          'Injustice, dishonesty, failure to take responsibility, deceitful practices, negative karma',
      yesOrNo: 'Neutral',
      description:
          'In the upright position, the Justice tarot card represents cause and effect as well as balanced thought and action. There are times when we find ourselves the victims of someone else’s malicious intent. If you have been wronged in any way, Justice arrives to restore balance and order. This isn’t to say that things will work out the exact way that you would like them to. However, pulling this card in reading does give support to the adage “All’s well that ends well.”',
      images: []),
  CardInfo(13,
      name: 'The Hanged Man',
      iconImage: 'assets/major/tarot-hangedman.jpg',
      suit: 'Major Arcana',
      upright:
          'Letting go, sacrificing, pausing to reflect, uncertainty, spiritual development',
      reversed:
          'Discontentment, stagnation, negative patterns, no solution, fear of sacrifice',
      yesOrNo: 'Maybe',
      description:
          'The Hanged Man represents ‘the waiting game’ that is often a part of life progression. Although we are rarely happy about being stuck in limbo, there are times when nothing else can be done, and we are forced to be still. This often requires the sacrifice of people and things that we would rather hold on to. The Hanged Man tarot card wants you to know that sometimes, we have to accept a loss for the greater good. Acceptance and letting go are key if you ever want to move forward.',
      images: []),
  CardInfo(14,
      name: 'Death',
      iconImage: 'assets/major/tarot-death.jpg',
      suit: 'Major Arcana',
      upright:
          'Ending of a cycle, transitions, getting rid of excess, powerful movement, resolutions',
      reversed:
          'Resisting change, fear of new beginnings, dependency, repeating negative patterns',
      yesOrNo: 'Yes',
      description:
          'One of the reasons that the Death card is such a powerful one in the Upright position is because it carries so many different meanings. For many readings, the Death tarot card signifies completing a chapter, putting the past behind you, and cutting out what is unnecessary. It can also signify a transition or middle ground between one phase of life and the next. The key is to welcome the Death card in a tarot spread instead of avoiding it. What path is number thirteen trying to point you toward? After all, there is no new beginning without an ending.',
      images: []),
  CardInfo(15,
      name: 'Temperance',
      iconImage: 'assets/major/tarot-temperance.jpg',
      suit: 'Major Arcana',
      upright:
          'Balance, moderation, good health, cooperating with others, finding solutions',
      reversed:
          '	Imbalance, discord, hastiness, overindulgence, risky behavior',
      yesOrNo: 'Yes',
      description:
          'Avoid all extreme situations when pulling the Temperance card in your reading. Although there are times to ‘go for the jugular,’ this is not the angel’s message. Some situations are complicated and require patience and special care, even when your emotions are telling you to react. Temperance is actually a skill, and like any other skill, practice makes perfect. Hold back from quick judgment. Resist the temptation to react immediately. Are there areas of your life in which you need to find balance? Could you benefit from learning to remain calm during moments of distress? Temperance has arrived to help you find the strength to do so.',
      images: []),
  CardInfo(16,
      name: 'The Devil',
      iconImage: 'assets/major/tarot-devil.jpg',
      suit: 'Major Arcana',
      upright:
          'Material focus, trapped in bondage, addictions and depression, negative thinking, betrayal',
      reversed:
          'Overcoming addiction, independence, reclaiming power, detachment, freedom',
      yesOrNo: 'No',
      description:
          'The Devil is the card of illusion. Although you have total control of your life, beliefs, and choices, the Devil card symbolizes how addiction, depression, and unhealthy bonds can make you feel out of control. Even social media, exercise, and work can be embodied by the Devil when in excess. Regardless of the nature of your particular problem, the message of the Devil is clear: redirect your attention away from the satisfaction of desires and toward the things that really matter.',
      images: []),
  CardInfo(17,
      name: 'The Tower',
      iconImage: 'assets/major/tarot-tower.jpg',
      suit: 'Major Arcana',
      upright:
          'Intense and sudden change, release, painful loss, tragedy, revelation',
      reversed:
          'Resisting change, avoiding tragedy, a narrow escape, delaying what is inevitable',
      yesOrNo: 'No',
      description:
          'If we had to redesign the Tower card to a more modern-day representation, a crashing airplane would be an accurate alternative image. The Tower signifies total destruction. If you’ve received the Upright Tower tarot card, prepare for things to be leveled and dismantled. As with all losses, this will probably be a painful process. It can also lead to a fresh start. Before you are able to make these positive changes, you’ll have first to face the truth about a situation. Are you prepared to take your blinders off take this personal crisis head-on? Seeing through illusions and letting go of what you wish things to be is the very first step.',
      images: []),
  CardInfo(18,
      name: 'The Star',
      iconImage: 'assets/major/tarot-star.jpg',
      suit: 'Major Arcana',
      upright: 'Hope, renewal, creativity and inspiration, generosity, healing',
      reversed:
          'Despair, lack of hope, creative block, boredom, focusing on the negative',
      yesOrNo: 'Yes',
      description:
          'The universe abundantly blesses you (we). We are continually attracting what we desire through our beliefs and thoughts. When the Star arrives in the upright position, it usually follows a difficult change or traumatic event. Going through something challenging can take the wind out of our sails and cause us to feel like things will never be the same. This might be true. Death, loss, heartbreak, and other painful events can change who we are, forever. This doesn’t mean we can’t build something better. What is it that you are trying to heal from? The Upright Star wants you to open your heart, realize your inner strength, and have faith that the best is yet to come.',
      images: []),
  CardInfo(19,
      name: 'The Moon',
      iconImage: 'assets/major/tarot-moon.jpg',
      suit: 'Major Arcana',
      upright: 'Fear, anxiety, confusion, delusion, risk',
      reversed:
          'Overcoming fear, finding the truth, conquering anxiety, gaining clarity',
      yesOrNo: 'No',
      description:
          'When the Moon tarot card appears in a reading upright, it can mean that you are allowing your imagination and emotions to take control of your life. This may be linked to anxieties, fears, or self-deception. The Moon falling in a reading is a warning in a sense. You are the crawfish rising from the sea. If you trust your intuition and push forward, you will receive deliverance from what binds you. But first, you must be willing to face the reality of the situation. The upright Moon can also be some illusion. There may be a hidden truth in your life that you need to uncover. The Moon cautions you from accepting what things seem to be. It may be time to dig a little deeper and allow the light to shine upon the fallacies in your life.',
      images: []),
  CardInfo(20,
      name: 'The Sun',
      iconImage: 'assets/major/tarot-sun.jpg',
      suit: 'Major Arcana',
      upright: 'Happiness, fertility, success, optimism, truth',
      reversed: 'Sadness, procrastination, pessimism, lies, failure',
      yesOrNo: 'Yes',
      description:
          'The Sun tarot card in the upright position shows positivity and fulfillment in your life. If you have been going through a hard time and the Sun falls in an upright position, things will quickly improve. The Sun reminds us to look at the bright side of things and remind ourselves that hard times don’t last forever. Even when we are faced with difficulties, we can choose to ‘make lemonade out of lemons’ and embrace life lessons for what they are: learning tools. With these lessons under your belt, struggles and sadness will soon be left in the past, and you will be moving on to brighter and better days. You can rest assured knowing that good things are in store for you if this Major Arcana card is front and center.',
      images: []),
  CardInfo(21,
      name: 'Judgement',
      iconImage: 'assets/major/tarot-judgement.jpg',
      suit: 'Major Arcana',
      upright:
          'Reflection, inner calling, reckoning, awakening, rebirth, absolution',
      reversed: 'Feeling down, self-doubt, missing the call fearlessness',
      yesOrNo: 'Neutral/Yes',
      description:
          'Now is the perfect time to weigh your actions and see to it that they are in line with your values and beliefs. The things that you did in the past or are doing today – do they reflect your core values and belief? Do they direct you to your goals and purpose? Without having the clarity of knowing who you truly are, you cannot answer these questions. Take time to ponder on things before going on with your life. In the end, this will be worth it. Another possible indication is to remind you that there may be choices and vital changes that you will face and you cannot avoid them. If you have made some in the past, there will be an effect on where you are right now. Moreover, you should face the consequences with an open mind. You can’t do anything about the past – of what is done – and moving forward is your best bet.',
      images: []),
  CardInfo(22,
      name: 'The World',
      iconImage: 'assets/major/tarot-world.jpg',
      suit: 'Major Arcana',
      upright: 'Fulfillment, harmony, completion, integration, travel, unity',
      reversed: 'Incompletion, shortcuts, delays, emptiness',
      yesOrNo: 'Yes',
      description:
          'To encounter the upright World card in a tarot reading is to encounter success and accomplishment. It means that a long-term project, period of study, or any other major event in your life has come full circle and that you accomplished your goals and aspirations. Despite the difficulties and hardships you’ve encountered, you stood strong and persevered. The seeds you have planted are now blooming and you are reaping the fruit of your labor. Everything has come together, and you are in the right place, doing the right thing, achieving what you have envisioned. Be proud of what you’ve learned along the way, the progression you’ve made, and your achievements so far. Reflecting on what you’ve already accomplished, may just be what you need to bring your project to completion.',
      images: []),
  CardInfo(23,
      name: 'Ace of Wands',
      iconImage: 'assets/wands-14/tarot-wands-01.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Creativity, enthusiasm, breakthrough, a fresh start',
      reversed: 'Few options, fear of the unknown, sudden change',
      yesOrNo: 'Yes',
      description:
          'The Ace of Wands encourages energetic movement toward activity. Brace yourself and get ready to spring into action. You may need to make your move soon, so make sure you are fully prepared. Trust your instincts and spontaneity. When the opportunity comes, you may want to seize it without hesitation. So quicken your senses and raise your antenna. There is excitement in the air, and supports your immediate ambitions.',
      images: []),
  CardInfo(24,
      name: 'Two of Wands',
      iconImage: 'assets/wands-14/tarot-wands-02.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Decisions, travel, discovery, partnership, personal power',
      reversed: 'Few options, restlessness, fear of the unknown, sudden change',
      yesOrNo: 'Maybe',
      description:
          'The Two of Wands advises you to respect your own decision making process. Instead of criticizing yourself for indecisiveness, appreciate the various implications of possible choices. Avoid pushing yourself to make a commitment. Keep meditating, watching the situation and witnessing the forces at work. At some point you will have enough information to see clearly. The decision-making process will be over and the choice will be clear.',
      images: []),
  CardInfo(25,
      name: 'Three of Wands',
      iconImage: 'assets/wands-14/tarot-wands-03.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Exploration and travel, leadership, moving forward',
      reversed: 'Self-doubt, regret, perceived failure',
      yesOrNo: 'Yes',
      description:
          'The Three of Wands advises you to act quickly and powerfully on an idea or desire you’ve been feeling. This card suggests exquisite timing, staying in the moment and responding to your instinct or intuition. Every fiber of your being may be saying this is a great opportunity, even if those around you aren’t as convinced. There’s nothing to lose from taking a risk; this is a great moment in your entrepreneurial growth. Make your move and sort out the details later.',
      images: []),
  CardInfo(26,
      name: 'Four of Wands',
      iconImage: 'assets/wands-14/tarot-wands-04.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Celebration, excitement, homecoming, family unity',
      reversed: 'Unhappy family, cancellations, feeling unwelcome',
      yesOrNo: 'Yes',
      description:
          'The Four of Wands supports your good, productive, evolutionary ideas. Concentrate on networking: use your charisma and power to attract like-minded souls so you can significantly increase your sphere of influence -- the more people you can reach, the better. Your enthusiasm empowers your vision, which is thriving with possibilities. As you share more freely what is on your mind and in your heart, others will see themselves in your vision, so you naturally receive approval, support, assistance and abundance. In your own way, you are addressing a universal need.',
      images: []),
  CardInfo(27,
      name: 'Five of Wands',
      iconImage: 'assets/wands-14/tarot-wands-05.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Competition, disagreements, rivalry, challenges',
      reversed: 'Compromise, teamwork, harmony, solutions',
      yesOrNo: 'No',
      description:
          'The Five of Wands encourages you to find your natural ambition. Identify what energizes you, what you would fight for and what you are passionate about -- even when you are tired or discouraged. Strive to make that the centerpiece of your mission. This is how you find your livelihood and establish your path of service.',
      images: []),
  CardInfo(28,
      name: 'Six of Wands',
      iconImage: 'assets/wands-14/tarot-wands-06.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Victory, triumph, recognition',
      reversed: 'Failure, losing, broken promises, fame-hungry',
      yesOrNo: 'Yes',
      description:
          'The Six of Wands advises taking action on your most burning and passionate convictions, no matter what the social consequences. Continue to articulate and define yourself in light of the torch you are carrying. This inspires others to conceive some new ideas of their own. You may find yourself becoming something of a leader. Usually the first person to break away from conventional thought is the one to define a new trend. Under the circumstances, there is a solid need for a fresh voice and vision -- so make your move. Those around you who are ready for change will support your leadership.',
      images: []),
  CardInfo(29,
      name: 'Seven of Wands',
      iconImage: 'assets/wands-14/tarot-wands-07.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Conviction, strong-willed, defiant, determined',
      reversed: 'Exhaustion, compromise, teamwork, harmony, solutions',
      yesOrNo: 'Yes',
      description:
          'The Seven of Wands tells you that the time for peak performance is now. Even if slightly unprepared, you may want to push yourself beyond your usual limits, thinking in larger terms and tweaking your competitive nature. Time and effort spent in preparation could pay off handsomely. You might be the one who vaults right over the heads of those who thought they could outdo you. Move beyond rhetoric and verbal challenges. Now could be the moment to prove what puts your head and shoulders above the rest by demonstrating it in action.',
      images: []),
  CardInfo(30,
      name: 'Eight of Wands',
      iconImage: 'assets/wands-14/tarot-wands-08.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Quick action, receiving news, gaining momentum, exciting times',
      reversed:
          'Restriction, bad timing, getting a late start, losing traction',
      yesOrNo: 'Yes',
      description:
          'With the Eight of Wands, learn all you can from recent successful experiences. Take note of what worked before and what didn’t. You possess awareness as to how to effectively apply your imagination to shape the world in productive and aesthetic ways. Thus, the testament to your talents may be revealed for everyone to see and admire. Even if you had to leave it all behind, you know you could start all over among total strangers and succeed once again. This valuable self-confidence makes you free to strike out in new directions and not just cling to past successes and previous accomplishments.',
      images: []),
  CardInfo(31,
      name: 'Nine of Wands',
      iconImage: 'assets/wands-14/tarot-wands-09.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Perseverance, stamina, courage',
      reversed: 'Stubbornness, no compromise, lack of trust',
      yesOrNo: 'No',
      description:
          'When the Nine of Wands is in this position, you have done everything you can to bring a situation to a successful conclusion. The full range of possibilities has been exhausted and all the creative energy that is available has already been put to use. This may be a great time to lay down your concerns and enjoy a rest. There’s nothing more to bring to the mission unless you regenerate and restore the energy you have put into the cause. While it is praiseworthy to give all you have for something or someone that means a lot to you, masochism and martyrdom are ill advised. Take a break. No one can fault you for it now.',
      images: []),
  CardInfo(32,
      name: 'Ten of Wands',
      iconImage: 'assets/wands-14/tarot-wands-10.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Struggling, overextending, feeling burdened',
      reversed: 'Undependable, stress, procrastination',
      yesOrNo: 'No',
      description:
          'The Ten of Wands advises you to remember the true, simple heart of your youth and all the idealism it held. Now may be the time to reach deep into yourself and identify your purest, most wholesome impulses. As you do this, allow your optimistic and honorable side to see what is good about the world. Look beyond the challenges, setbacks, disappointments and frustrations you tend to see so easily. As you reawaken your high minded inner child, you will refresh your daily life with a joyful purpose.',
      images: []),
  CardInfo(33,
      name: 'Page of Wands',
      iconImage: 'assets/wands-14/tarot-wands-11.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Outgoing, child-like cheerfulness, creative confidence',
      reversed: 'Bad news or intentions, easily tricked, loudmouth, impatient',
      yesOrNo: 'Yes',
      description:
          'This card is traditionally entitled a Page, but in some modern decks as a Princess. This card suggests that you cannot know how to facilitate communication until you have studied your environment. Your task may be to blend into your surroundings so you can gather information and get a clear sense of what’s going on around you. Think of yourself as a secret agent for the greater good. In due time, others may recognize the role you play in the transformation from divisiveness to unity. However, right now you are being asked to watch quietly from the sidelines.',
      images: []),
  CardInfo(34,
      name: 'Knight of Wands',
      iconImage: 'assets/wands-14/tarot-wands-12.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Charming, self-confident, daring, passionate',
      reversed: 'Superficial, cocky, foolhardy, restless',
      yesOrNo: 'Yes',
      description:
          'The Knight of Wands (in some decks, a Prince) advises that you modify your self-image in order to get a sense of yourself as a person of action. No matter what your past patterns have been, it is fully possible to place yourself solidly on the road toward the future. Not only can you get a clear sense of the proper path, but you will also have enough instructions to be self-directing. Necessary skills and resources are available to you, and the time is right for you to act. Once you get started, you may be surprised how easy it can feel, but don’t be seduced by that feeling. There will be comfortable stretches of the road and there will be distinctly uncomfortable ones. Know that any form of motion is better than no motion.',
      images: []),
  CardInfo(35,
      name: 'Queen of Wands',
      iconImage: 'assets/wands-14/tarot-wands-13.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Fiery passion, energetic, self-assured, wholehearted',
      reversed: 'Jealous, hot-tempered, selfishness, insecurity',
      yesOrNo: 'Yes',
      description:
          'The Queen of Wands reveals a need to hold your place in the chain of command and respect the hierarchy (at least for now). This may not be a time for you to be at the helm, even if you are motivated by a strong dedication to completing a project or overcoming a challenge. A perceived deficiency in leadership may make you want to take hold of the reins, but don’t do it! Restrain yourself and remain loyal to your higher-ups. Stay focused and energetic. Enthusiastically confront the challenges directly in front of you. Perform in good faith and encourage others to do the same.',
      images: []),
  CardInfo(36,
      name: 'King of Wands',
      iconImage: 'assets/wands-14/tarot-wands-14.jpg',
      suit: 'Minor Arcana - Wands',
      upright: 'Protective, innovative, inspiring, magnetic',
      reversed: 'Forceful, impulsive, broken promises, extremism',
      yesOrNo: 'Yes',
      description:
          'The King of Wands reminds us that our lives are designed to bring us eventually to a place of self-ownership. An opportunity for self-empowerment is presenting itself to you now. Recognize that through your attitude and the way you express yourself to others, you hold the power over your own experiences in life. You are the determining factor in this situation and circumstances will proceed in the direction that you steer them. Indecision or doubt are not appropriate responses when clarity and confidence are critical. As you take on a bigger role, it’ll begin to feel more comfortable. Seize the opportunity to influence events, because everything is waiting for you.',
      images: []),
  CardInfo(37,
      name: 'Ace of Cups',
      iconImage: 'assets/cups-14/tarot-cups-01.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Happiness, fulfillment, new beginnings',
      reversed: 'Anguish, end of a relationship, bad news ',
      yesOrNo: 'Yes',
      description:
          'The Ace of Cups advises you to challenge yourself and discover what’s good about every relationship. Practice looking at the world through the eyes of the Divine. Allow your imagination to perceive the spiritual or evolutionary potential in every person and experience. Look with the eye of a loving parent or companion upon the people and things you come into contact with. Make a conscious decision to approve of and delight in even the quirky developments that make the world turn. No one can be perfect at such unconditional acceptance. Still the practice will sweeten your day to day life. Your magnetism will increase and more loving people may enter your life. The whole world will benefit as this becomes second nature to you.',
      images: []),
  CardInfo(38,
      name: 'Two of Cups',
      iconImage: 'assets/cups-14/tarot-cups-02.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Happiness, relationships, love',
      reversed: 'Arguments, strained relations, anguish',
      yesOrNo: 'Yes',
      description:
          'The Two of Cups advises you to speak your heart. It may be likely that the person you are trying to connect with feels the same. Still the other needs to hear this more fully. So why not make it clear and why not now? The Two of Cups is the image of the heart making a vow. This card advises that you pledge yourself to this friendship and put your heart on the line. You have nothing to lose and everything to gain. Life is a relationship game. It’s a great privilege to share with others who are so complementary and compatible.',
      images: []),
  CardInfo(39,
      name: 'Three of Cups',
      iconImage: 'assets/cups-14/tarot-cups-03.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Celebrations, good conversation, happiness',
      reversed: 'Neglected social life, cheating, gossip, frustration',
      yesOrNo: 'Yes',
      description:
          'The Three of Cups advises that you tune in with your family and fully inform them about what is going on with you. Let them add substance to your ideas with their talent and imagination. Think of this occasion as a celebration, where their support helps you find success in your work. There may be something here for everyone to contribute. Put yourself in the loving hands of your family connections and your trust will be well rewarded. The synergy between you could enhance each individual is talent and creativity. You will love the results!',
      images: []),
  CardInfo(40,
      name: 'Four of Cups',
      iconImage: 'assets/cups-14/tarot-cups-04.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Depression, missed opportunities, feeling stuck',
      reversed: 'Passion, taking action, moving forward',
      yesOrNo: 'Maybe',
      description:
          'The Four of Cups wants you to take a clear look at how stalled or distracted you have become. You may have been bogged down by negativity, hopelessness or a sense of limitation. It’s not to your advantage, however, to see the world through such a narrow lens. Cut through some of the forces that undermine you, causing you to feel incapable. Sometimes you have to define what you are "for" by defining what you are "against." Decide that you are not as heavy as the cup of earth, not placid as is the cup of water, not turbulent as is the cup of air. Rather, now may be the time to be as aroused as is the cup of fire. This arousal may constitute liberation from the circumstances that may have brought you here.',
      images: []),
  CardInfo(41,
      name: 'Five of Cups',
      iconImage: 'assets/cups-14/tarot-cups-05.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Sadness, loss, despair, loneliness',
      reversed: 'Finding peace, acceptance, healing',
      yesOrNo: 'No',
      description:
          'The Five of Cups advises you to tighten your belt, make do with less and show more appreciation for the things you do have. If something is truly yours, it can’t be lost. When you are experiencing feelings of loss, it may be because of an inappropriate emotional attachment. If you promise things that you can’t deliver, then you might be setting yourself up for disappointment to follow. In overestimating our abilities, we are forced to face our limits. Be grateful that as the cups fell, you lost only three of the five. Two are still intact, pristine and full of sacred energy. Don’t cling to the setback. Focus on the potential.',
      images: []),
  CardInfo(42,
      name: 'Six of Cups',
      iconImage: 'assets/cups-14/tarot-cups-06.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Playful, carefree, nostalgic, children',
      reversed: 'Maturity, boredom, independence',
      yesOrNo: 'Yes',
      description:
          'When the Six of Cups is in this position, take a look at what is repetitive or cyclical in your life; what links the present situation to the last such experience. A new beginning requires new energy and concentration. Until you analyze the past, you will continue to drift with its current. Distill everything that is worthwhile from your memories and get as much value from it as you can. Then use this as motivation for change. Make the very best use of hindsight, employing new strategies and trying new angles on these recurring issues.',
      images: []),
  CardInfo(43,
      name: 'Seven of Cups',
      iconImage: 'assets/cups-14/tarot-cups-07.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'An abundance of options, choices, opportunities',
      reversed: 'Bad decisions, returning to reality, feeling trapped',
      yesOrNo: 'Maybe',
      description:
          "The Seven of Cups in this position advises that you relax your mind and open to the dreams and imaginings your inner child loves to entertain. Allow yourself to imagine a truly positive outcome for this situation. Perform an exercise in creative visualization by relaxing your guard and letting go of your fears. As the dreamscape unfolds, your electro-magnetic chemistry is stimulated to a point of achieving greater confidence in yourself and in what you are doing. Even if it's only a temporary break from your fears, this is a helpful exercise because it gives your psyche and body a dose of unlimited thinking and optimism. Think positively -- the results could truly be amazing.",
      images: []),
  CardInfo(44,
      name: 'Eight of Cups',
      iconImage: 'assets/cups-14/tarot-cups-08.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Abandonment, travel, end of a relationship, letting go',
      reversed: 'Scared to move on, stagnant, faking happiness',
      yesOrNo: 'No',
      description:
          "With the Eight of Cups in this position, look inside and recognize the part of you that still nurses an old grudge from a past injury or trauma. For the most part, your forward-looking self has gotten up and moved along. You are getting on with your life. There may still a part of you, however, that holds out and resists the healing. Are you nursing old wounds from painful losses of faith and trust? If so, now may be a good time to scrutinize your current motives. See if you are still being influenced by the part of yourself that cuts short your enthusiastic, optimistic impulses. Do not deny this pessimistic tendency. Failing to recognize the truth only causes repression that flares up in another part of our psyche. Instead, seek to understand and accept the hesitation and the fear you may feel, and come to terms with them. Then you can put some old emotions in their rightful place--out of the way.",
      images: []),
  CardInfo(45,
      name: 'Nine of Cups',
      iconImage: 'assets/cups-14/tarot-cups-09.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Wishes coming true, fulfilled dreams, prosperity',
      reversed: 'Shattered dreams, sadness, failure',
      yesOrNo: 'Yes',
      description:
          "The Nine of Cups in this position advises that you open yourself to circumstances around you. There may be no need to manage a situation that does not require a lot of control or leadership. The tone of the moment is heartfelt and bonded. It is nurturing. Open up and choose to be receptive. Proceed from your heart, relying on your intuition. This is your truest source of information right now. Allow yourself to be attracted to what feels supportive. Avoid what feels harsh, critical and judgmental. If this requires that you change your style, so be it. The results of being intuitive are generally far superior to the results of being emotionally guarded and overly rational.",
      images: []),
  CardInfo(46,
      name: 'Ten of Cups',
      iconImage: 'assets/cups-14/tarot-cups-10.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Happiness, family, family reunions, harmony',
      reversed: 'Despair, broken family, divorce/separation, conflict',
      yesOrNo: 'Yes',
      description:
          "With the Ten of Cups in this position, prioritize teamwork over your personal goals. Everyone needs to feel they made a contribution. The crew needs to feel they are all in this together, and everyone needs to be rewarded when the ship comes in. It's essential to follow a teamwork approach in order to maximize the benefits for yourself. The good will that will emerge from such an approach will last long after the project is over. You will be generously rewarded later if you take a selfless approach at this time.",
      images: []),
  CardInfo(47,
      name: 'Page of Cups',
      iconImage: 'assets/cups-14/tarot-cups-11.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Idealism, youthfulness, good news',
      reversed: 'Immaturity, broken dreams, envy',
      yesOrNo: 'Yes',
      description:
          "The Page of Cups (in some decks, a Princess) in this position advises you to study the best ways to be of service. Strive to discern what would give more pleasure, comfort and emotional security. Then, provide it. Understand that what is happening has little or nothing to do with you personally. The best you can do is to offer support and listen closely. Make sure you understand what is needed and serve the situation with loyalty. Look at individuals around you as the embodiment of the Divine, and try to fulfill each one's needs. Be unconcerned with the outcome. Later you will understand why you needed to be in this position.",
      images: []),
  CardInfo(48,
      name: 'Knight of Cups',
      iconImage: 'assets/cups-14/tarot-cups-12.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Romantic proposals, invitations, following your heart',
      reversed: 'Heartbreak, cheating, deception',
      yesOrNo: 'Yes',
      description:
          "The Knight of Cups (in some decks, a Prince) in this position advises that you jump into your new situation with both feet. Get involved with what is happening in the present. Think no more about the route you had to travel to get back here. There is no need to be cavalier about what seems familiar. Look deeply at the underlying values here. You may find that they represent something you mistakenly rejected in the past. Be humble enough to look at things through new eyes. At a deep level, your heart and soul are being nourished. Don't be tempted to run away again -- this is where you belong. Your entire journey was designed to bring you home with new appreciation.",
      images: []),
  CardInfo(49,
      name: 'Queen of Cups',
      iconImage: 'assets/cups-14/tarot-cups-13.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Femininity, loving, kindness, sensitivity',
      reversed: 'Insecurity, weak, needy, shallow',
      yesOrNo: 'Yes',
      description:
          "The Queen of Cups in this position encourages you to be generous, kind and forgiving. Support the ability of others to get what they want. Nevertheless, remember as with anyone in a caretaking position, you have a fine line to walk. You do not want your loved ones or teammates to become complacent or dependent, as if they can take your support for granted with little or no consideration for your needs. Cultivate an awareness of love as freely giving and receiving. In the process, help clarify the important difference between receiving energy and taking it. Do not allow your willingness to give be misunderstood or abused, as if it were a weakness.",
      images: []),
  CardInfo(50,
      name: 'King of Cups',
      iconImage: 'assets/cups-14/tarot-cups-14.jpg',
      suit: 'Minor Arcana - Cups',
      upright: 'Good advice, creativity, wisdom',
      reversed: 'Unproductive, unreliable, intolerant',
      yesOrNo: 'Yes',
      description:
          "The King of Cups in this position advises that you closely examine your conscience and bring your personal mission into alignment with what is best for everyone. You can then step into your community or situation with integrity and an ability to communicate the highest wisdom. As this sweetens the environment, others will be inspired to raise their own motives and intentions to match yours. You will be providing an important kind of leadership that uses strong reassurance to help everyone work together. The most persuasive thing about you is the example of generous behavior that you exhibit -- much more powerful than preaching alone.",
      images: []),
  CardInfo(51,
      name: 'Ace of Swords',
      iconImage: 'assets/swords-14/tarot-swords-01.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Clarity, sound decision making, a breakthrough, opportunities',
      reversed: 'Unproductive, irrational, destruction, missed opportunities',
      yesOrNo: 'Yes',
      description:
          'The Ace of Swords in this position advises you to be steady--you are about to reach your objective. There may be no need to hesitate. Just concentrate on making your impact. This could be your moment. The arrow is pointed straight at the target. Your eye is keen, your grip is firm. Let that arrow fly! If you set aside distractions and hit your mark, you will be rewarded with insight and clarity. Remember that this is not the time to hold back, worrying about the consequences. When you access this level of truth, you are very likely to cut through all illusion and nonsense.',
      images: []),
  CardInfo(52,
      name: 'Two of Swords',
      iconImage: 'assets/swords-14/tarot-swords-02.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Stalemate, coming to crossroads, time to think',
      reversed: 'Emotional detachment, indecision, deception',
      yesOrNo: 'Maybe',
      description:
          'The Two of Swords in this position advises that this may not be a good time to make a decision. Neither allow others to push you beyond your boundaries, nor permit yourself to act impulsively. You need to fully assimilate the situation before making any moves -- even if not having a solution as soon as you want causes tension. Have patience. There are circumstances in which action is better than non-action. This, however, is not one of them. Remain silent as much as possible and allow things to settle. A little meditation can help you achieve greater objectivity. You do not have enough information, as all the evidence has not come in yet.',
      images: []),
  CardInfo(53,
      name: 'Three of Swords',
      iconImage: 'assets/swords-14/tarot-swords-03.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Heartbreak, loneliness, betrayal, sadness, grief',
      reversed: 'Optimism, acceptance, perseverance, forgiveness',
      yesOrNo: 'No',
      description:
          'The Three of Swords in this position advises you to strike out on your own. Become more independent. Separate yourself from people and forces you do not feel compatible with. Grow a thicker skin. Use your creativity and imagination and seek out situations where the way you see things makes sense to those around you. Move towards those who can embrace and appreciate your talents and all you have to contribute.',
      images: []),
  CardInfo(54,
      name: 'Four of Swords',
      iconImage: 'assets/swords-14/tarot-swords-04.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Anxiety, chronic stress, chaos',
      reversed: 'Rejuvenated, mental peace, relaxation',
      yesOrNo: 'Maybe',
      description:
          'The Four of Swords in this position strongly urges that you keep your own counsel in this situation. There may be too much fear and hostility in the environment for you to be heard. It might be that your ideas are not ripe enough or that you are not ready to listen to feedback from others. If you spend more time in contemplation, you may successfully disregard the emotional occupations and biases of others. For now, closely observe inner events. The time for sharing will come later.',
      images: []),
  CardInfo(55,
      name: 'Five of Swords',
      iconImage: 'assets/swords-14/tarot-swords-05.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Battles, arguments, conflict, defeat, surrender',
      reversed: 'Compromise, moving forward, solutions to a conflict',
      yesOrNo: 'No',
      description:
          'The Five of Swords in this position advises you to prepare yourself for disappointment over how your fellow humans are setting their priorities. It seems that the lower end of human nature may be eroding good will in the current situation. Due to a strong cultural trend toward scarcity thinking, a "me first" outlook prevails. If this means that you need to develop a thick skin or carry your sword of truth closer, then do so. Try not to be too quick to anger or jump to conclusions. Just because others may have a pessimistic sense of the world, their reality does not have to undermine yours. There is certainly no point in struggling or competing with them. Your challenge now is to learn how to sidestep confrontation and evoke a more evolved response from people. At the very least, be assertive about setting boundaries for yourself.',
      images: []),
  CardInfo(56,
      name: 'Six of Swords',
      iconImage: 'assets/swords-14/tarot-swords-06.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Letting go of hatred, healing, moving forward, escape',
      reversed: 'Feeling overwhelmed, slow healing, trapped',
      yesOrNo: 'Yes',
      description:
          'The Six of Swords in this position reminds you that time is of the essence. You have seen the big picture, and good ideas have occurred to you about what needs to be done. Now it is necessary to take action. There may be no more time for debate. If the game plan has become clear, your next step could be to commit yourself to pursue changes that will lead to improvement. Overcome the tendency to get distracted. You do not have time for approval seeking. Once you initiate action, others will be grateful for your clear thinking and quick reflexes. It is a special gift to be able to navigate in times of rapidly changing and unpredictable circumstances, when a cool head and right timing are most essential.',
      images: []),
  CardInfo(57,
      name: 'Seven of Swords',
      iconImage: 'assets/swords-14/tarot-swords-07.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Dishonesty, deceit, manipulation, cheating, theft',
      reversed: 'Taking responsibility, starting fresh, coming clean',
      yesOrNo: 'No',
      description:
          'The Seven of Swords in this position suggests that deep within you already know exactly what has to happen. You know what steps to take and what order to take them in to bring about a desirable outcome in this situation. You may have enough of an overview to see how to advance through the maze and achieve your goal. Continue to envision unobstructed success. Even as the path you are walking changes and the circumstances around you obscure your view, keep the desired outcome clear and sharp in your mind. You will quite likely reach your goal and gain tremendous self esteem in the process.',
      images: []),
  CardInfo(58,
      name: 'Eight of Swords',
      iconImage: 'assets/swords-14/tarot-swords-08.jpg',
      suit: 'Minor Arcana - Swords',
      upright:
          'Feeling stuck, unproductive, feeling trapped, hopeless, helpless',
      reversed:
          'Being productive, finding a way out, taking control, a light at the end of the tunnel, freedom',
      yesOrNo: 'No',
      description:
          'With the Eight of Swords in this position, you are being reminded that every setback you experience is a teacher awakening you to renewed effort. This is a learn-by-doing situation; there is no formula that guarantees outcome. You can be sure, however, that an open-minded and optimistic attitude will serve you better in the face of surprising developments. Be willing to make the rigorous effort that is being called for now. Perform wholeheartedly, with good faith and hopefulness. As such, you will forestall bickering and criticism, prevail against negative forces and overcome the demons of doubt and resistance. Get excited about your challenges; be confident that you have what it takes to improve the situation. If you do your internal homework, the external situation will open up for you.',
      images: []),
  CardInfo(59,
      name: 'Nine of Swords',
      iconImage: 'assets/swords-14/tarot-swords-09.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Despair, hopelessness, anxiety, overreacting, anguish',
      reversed:
          'Gaining clarity, learning to cope, letting go of anxiety, optimism, recovering',
      yesOrNo: 'No',
      description:
          'The Nine of Swords in this position advises you to confront your fear of being alone and acknowledge the different limits you may have put on yourself because of that fear. In the name of being safe, you may have adhered to lower standards than you are capable of achieving. If so, then you may have resisted striking out on your own. Perhaps you have bargained away creativity and joy in order to avoid being challenged. These kinds of tradeoffs never work. This could be a time to cut your losses. If so, recognize how much time and energy you have sacrificed to a way of being that is not right for you. If you can do this you will look back at this time in your life as a turning point. This may be an opportunity to heal as you shed a heavy burden that weighs you down.',
      images: []),
  CardInfo(60,
      name: 'Ten of Swords',
      iconImage: 'assets/swords-14/tarot-swords-10.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Mental breakdown, betrayal, failure, enemies, financial ruin',
      reversed:
          'Finding new ways to cope, persevering, forgiveness, rising above enemies, building something new',
      yesOrNo: 'No',
      description:
          'The Ten of Swords in this position advises that you lay low for a while. Do not make a move. Keep yourself as safe as possible until the drama, even the possible trauma, plays itself out. Once the turmoil dies down, then you can assess the damage and start to make repairs. The situation can be compared to a hurricane moving through the neighborhood. You cannot be sure whether it is going to pass over a corner of the field or whether it is going to slam into your house. In the face of such unpredictability, protect yourself, hope for the best and wait it out. Sometimes, an extreme turn of events serves as a pressure relief valve for all the unexpressed and unresolved energy that had been building up. Trust the process even though things may seem pretty drastic right now.',
      images: []),
  CardInfo(61,
      name: 'Page of Swords',
      iconImage: 'assets/swords-14/tarot-swords-11.jpg',
      suit: 'Minor Arcana - Swords',
      upright:
          'Standing up for justice, youthful, inspiration, confidence, fairness',
      reversed:
          'Feeling unproductive, exhaustion, defensive, manipulation, playing mind games',
      yesOrNo: 'Yes',
      description:
          'When the Page of Swords (in some decks, a Princess) is in this position, the situation requires subtle change in order for it to be brought to the highest good for all concerned. In contrast to times when one can best serve the greater good by being visible and heroic, this is a time when you must keep your own counsel, cover your tracks and stealthily accomplish what would be impossible to complete without privacy. Reduce your profile and increase your anonymity, no matter how your self-image might suffer. Although it would be gratifying to accomplish what needs to be done and be aboveboard about it, that cannot be a priority at present.',
      images: []),
  CardInfo(62,
      name: 'Knight of Swords',
      iconImage: 'assets/swords-14/tarot-swords-12.jpg',
      suit: 'Minor Arcana - Swords',
      upright:
          'Bravery, accomplishment, big changes, seize the moment, tenacity',
      reversed:
          'Being stagnant, laziness, missed opportunities, go with the flow, self-doubt',
      yesOrNo: 'Maybe',
      description:
          'The Knight of Swords in this position advises you to remain open to conflicting ideas instead of surrounding yourself exclusively with people who agree with you. This Knight is most effective when testing his ideas in a debate. Emulate his ability to communicate successfully by keeping your conversations impersonal and humorous so no hurt feelings are provoked. Practice your negotiation skills so you will be in shape for imminent diplomatic challenges as they arise. A sparring partner could help you learn to control impulsive comments and stem your urge to be right at the expense of others being wrong.',
      images: []),
  CardInfo(63,
      name: 'Queen of Swords',
      iconImage: 'assets/swords-14/tarot-swords-13.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'Supportive, empathetic, encouraging, protective, independent',
      reversed: 'Careless, cruel, harsh, dangerous, cold-hearted',
      yesOrNo: 'Maybe',
      description:
          'The Queen of Swords in this position advises that you refrain from remaining dependent on others at this time. Instead of placing too much confidence in the promises people have made, harbor only those ambitions you know you can accomplish yourself. The Queen of Swords does not want to wait and see what others would think, say or do. She knows what she wants and how to get it. She does not ask permission or even subject herself to much influence. There are times in life when no one can take care of you as well as you can. Leave sentimentality behind and take action. Make important decisions for yourself because it is up to you. You are the final judge.',
      images: []),
  CardInfo(64,
      name: 'King of Swords',
      iconImage: 'assets/swords-14/tarot-swords-14.jpg',
      suit: 'Minor Arcana - Swords',
      upright: 'An astute man, authority, a leader, logical, fatherly',
      reversed: 'Irrational, abuse of power, lack of morals, absent father',
      yesOrNo: 'Maybe',
      description:
          'In this position, the King of Swords advises that you research your situation and in the process question existing authorities. It may be time to examine underlying assumptions and bring greater clarity into areas that have been left in the dark. Do not wait for others to do it. Instead, draw your own conclusions. Spend time reviewing all the ramifications because this King of Swords requires a thorough, methodical examination of ideas and possibilities. Call forth the sober and wise part of yourself -- the elder father figure. Then act on the instructions given you.',
      images: []),
  CardInfo(65,
      name: 'Ace of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-01.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'New beginnings, prosperity, gain, stability, abundance',
      reversed: 'Negativity, procrastination, frustration, poor planning',
      yesOrNo: 'Yes',
      description:
          "The Ace of Pentacles in this position advises that you apply nature's lesson of compound interest and develop your project gradually. A slow and steady buildup -- visible or invisible -- makes change and growth inevitable. Akin to the changing of the seasons, you do not notice this trend from day to day. As the year comes full circle, however, you cannot miss the changes. This card advises that if you work a little bit every day toward your long-term goal, at some time in the future you will discover that you have accumulated magnificent results. The secret of achieving success does not lie in inflating your dreams to grandiose levels; instead it comes about by choosing your direction wisely, while humbly and faithfully taking one step at a time.",
      images: []),
  CardInfo(66,
      name: 'Two of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-02.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'Finding balance, multi-tasking, perseverance',
      reversed: 'Imbalance, lack of organization, overextending',
      yesOrNo: 'Maybe',
      description:
          'The Two of Pentacles in this position advises you not to choose anything definitive for the time being. Give yourself a little more time to sort out your feelings and any mixed messages you may be receiving from others. Ask yourself -- are all the facts in yet? Or is the coin still flipping in the air? There is no need to be goaded into premature decisions or actions. Act only when you are able to do so with a unified heart and mind.',
      images: []),
  CardInfo(67,
      name: 'Three of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-03.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright:
          'Teamwork, focused effort, growth and learning, mastery, recognition',
      reversed: 'Lack of collaboration, no motivation, few goals, misalignment',
      yesOrNo: 'Yes',
      description:
          'The Three of Pentacles in this position suggests that you showcase your unique capabilities. Let the world in on who you really are. This is a good time to seek recognition. Once you receive the appreciation you deserve, accept and savor the acknowledgment. Expect new and exciting offers. When they arrive, accept them graciously. Why hide your light under a bushel? It does not become you to display false modesty. Practice saying to yourself, "Thank you, I accept the compliment" until you learn to fully let in this kind of affirmative grace with ease.',
      images: []),
  CardInfo(68,
      name: 'Four of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-04.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'A need for control, greed, materialism, blocking change',
      reversed:
          'Release of the past, giving up control, generosity, acceptance',
      yesOrNo: 'Yes',
      description:
          "The Four of Pentacles in this position signifies a young person, naive and pampered, who has been left an estate. Think conscientiously about all those people whom your activities impact, including those whose work and effort went into building what you inherited and those whose welfare depends upon your right management. What you have been given is abundant; still, it is not without limits. If you are prudent and responsible, the endowment will grow. However, if you are frivolous or foolish, your behavior could undermine both your inheritance and the well being of others who are connected to it. In many decks, we see the image of a person who is stuck in his or her misunderstanding of how the material plane works. He's afraid to let go of his four measly pentacles, because he doesn't know he has to give in order to get. When looked at this way, this is the card of 'poverty consciousness.'",
      images: []),
  CardInfo(69,
      name: 'Five of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-05.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright:
          'Financial hardship, struggle, lack of faith, rejection, sickness',
      reversed: 'Luck, triumph, better health, improved finances, recovery',
      yesOrNo: 'No',
      description:
          'The Five of Pentacles in this position advises you to create contractual agreements with those around you who have similar interests. In this kind of situation, there is strength in numbers. Put your heads together and devise a bold plan for future objectives and decide how to invest in their success. This Five of pentacles recommends teamwork and the mutual benefits a combined effort can yield. Note: In the English decks, like the Rider-Waite, the sickly poor freezing outside a well-lit church warn of the painful outcomes of bad choices, rather than focusing on the dynamic tension of the choosing itself.',
      images: []),
  CardInfo(70,
      name: 'Six of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-06.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'Generosity, shared wealth, prosperity, balance',
      reversed: 'Debt, one-sided relationships, desperation, dependence',
      yesOrNo: 'Yes',
      description:
          'The Six of Pentacles in this position asks you to think of yourself as a cosmic talent agent, seeking individuals who show a spark or gift. You may help them refine and upgrade their skills to fit a larger context. The outcome is a peer relationship with a sense of mutual regard and admiration. This is a delicate operation. You have to constantly check your intentions so that you are not expecting something in return. Do not for a minute feel proud about doing someone a favor. In truth what you are doing is paying back an old debt to those who served as your mentors.',
      images: []),
  CardInfo(71,
      name: 'Seven of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-07.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright:
          'Planning, hard work, perseverance, rewards and result, long-term success',
      reversed:
          'Lack of planning, poor management, laziness, delay, impatience',
      yesOrNo: 'Yes',
      description:
          "The Seven of Pentacles in this position advises you to focus on the long run. Look beyond this week or this month. This card exemplifies the magic of compound interest. You'll have much better results with a slow and steady investment of time, energy and labor than you would generate by trying to win the lottery. The path to success is paved by perseverance. Glamorous or flashy moves cannot take the place of consistent steps in the right direction. If you do not understand this, perhaps you are moving in the wrong direction or are not motivated strongly enough.",
      images: []),
  CardInfo(72,
      name: 'Eight of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-08.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright:
          'Ambition, diligence, mastery, crafts and talents, perfectionism',
      reversed: 'Lack of quality, workaholic, mediocrity, dead-end roads',
      yesOrNo: 'Yes',
      description:
          'The Eight of Pentacles in this position recommends that you focus on your main project and produce as much as you can, while staying healthy. This is an important time for meeting goals. However, do not work so hard that quality suffers. You are in a position where your effort can make a big difference. Apply yourself. Do the work and you will be rewarded with flexibility and freedom.',
      images: []),
  CardInfo(73,
      name: 'Nine of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-09.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'Independence, prosperity, refinement, comfortable life',
      reversed:
          'Financial dependency, success at all costs, pride, trapped in a hustle',
      yesOrNo: 'Yes',
      description:
          'The Nine of Pentacles in this position suggests that you prepare yourself for greater resources to be flowing in your direction. If you pay attention -- and keep the faith -- you can make a smooth transition into a state of well being and peace of mind. Hard work has brought you to a place where you could earn and receive grace, comfort, and freedom -- whether that be personal, emotional or financial. Exercise your imagination and create an abundant, sustainable, and enjoyable lifestyle (or relationship) for yourself. Acknowledge the friends and others who were loyal to you during the difficult times. Gather your dreams and get ready. You deserve this happiness.',
      images: []),
  CardInfo(74,
      name: 'Ten of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-10.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright:
          'Inheritance, affluence, tradition, a strong foundation, good family life',
      reversed:
          'Financial disputes, family feud, restriction, separation, general loss',
      yesOrNo: 'Yes',
      description:
          "The Ten of Pentacles in this position advises that you think of yourself as one who may be of great benefit to people. No matter whether it be a service, an invention or an idea -- you know you are holding a storehouse of value. Your potential treasure is enough to take care of you and yours for a long time. Exactly how are you going to administer the rewards of your talent? Recall the time when you began this current path or endeavor. Remember your sincerity, your innocence and your original vision. Can you reproduce success and sustain inspiration as the administrator of your present abundance? Think of every act of spending and investing and securing as the sowing of seed that will sprout and produce another money tree in somebody else's yard. How can you get really clever and inventive at throwing those seeds? This is your next assignment.",
      images: []),
  CardInfo(75,
      name: 'Page of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-11.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'Sticking to goals, practicality, loyalty',
      reversed: 'Procrastination, unrealistic goals, immaturity',
      yesOrNo: 'Yes',
      description:
          'The Page of Pentacles (in some decks, a Princess) in this position advises that you study your chosen field seriously, gaining intellectual knowledge plus whatever experiential learning you can pick up as well. Listen to the stories of others, both their successes and their failures, and let yourself be inspired by their dedicated efforts. Leave no stone unturned. See if you can figure out why their experiments went the way they did and what you might do differently that could change the outcome. Passionately hunt for the missing pieces overlooked by those who came before you. Remember that the mind of a beginner is an open channel for genius. Let that openness lead you and you will instinctively penetrate to the heart of the matter.',
      images: []),
  CardInfo(76,
      name: 'Knight of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-12.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'Consistency, strong will, improvement',
      reversed: 'Complacency, stubbornness, laziness',
      yesOrNo: 'Yes',
      description:
          'When the Knight of Pentacles (in some decks, The Prince) falls in this position you are being advised to offer up your services to some project or enterprise in front of you. Your willing participation can make the difference between a marginal performance and a great one. The entire endeavor will be enhanced significantly by the resources you bring to it and you will be blessed tenfold. Expect to supervise and guide the project as well as influence the outcome of events. Without you on board, this endeavor is just another good idea.',
      images: []),
  CardInfo(77,
      name: 'Queen of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-13.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright:
          'Nurturing healer, down-to-earth, gratitude, social consciousness',
      reversed:
          'Neglectful of self, smothering, obsessed with status, dependence',
      yesOrNo: 'Yes',
      description:
          'The Queen of Pentacles in this position advises you to trust the forces that have taken care of you up to this point. Continue to express your truth without worrying that you are going to lose the roof over your head or the bed you sleep in. It is your destiny to be safe and sound at this time in your life. Proceed with confidence and do what you so strongly feel must be done. Since the Queen of pentacles is often the person with the best intuition in the crowd, you may feel at first as if you are going against the grain, only to later find yourself becoming the leader of a new trend.',
      images: []),
  CardInfo(78,
      name: 'King of Pentacles',
      iconImage: 'assets/pentacles-14/tarot-pentacles-14.jpg',
      suit: 'Minor Arcana - Pentacles',
      upright: 'Enterprising, abundance, stability and security, groundedness',
      reversed:
          'Failing business, corruption, cold, materialistic, instability',
      yesOrNo: 'Yes',
      description:
          'The King of Pentacles in this position advises you to behave as if you already were a success. Project confidence that your plans and goals are in the process of unfolding perfectly. Make your moves with authority and trust in your actions without waiting for acknowledgment or approval. Soon enough you will receive blessing after blessing. If you can learn to feel that kind of confidence in your body and get comfortable with it as your natural state, you will attract the support you desire.',
      images: []),
];
